
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-06T14:28:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a30b5bc0156ee54a5823831fef069549b512a6f4",
 "version": "0.21.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
