
# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_short__',
    '__version_long__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_status__'
]

__version__ = '0.9.13'
__version_short__ = '0.9.13'
__version_long__ = '0.9.13-0-ga7ffc774'
__version_post__ = '0'
__version_commit__ = 'a7ffc774'
__version_date__ = '2018-06-17 00:05:37 -0400'
__version_dirty__ = False
__build_date__ = '2018-08-02'
__build_time__ = '18:29:41.597820'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
