
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-03T16:07:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "500c22e9c15f0b990bdc14dc1100ee64c1265f40",
 "version": "0.43.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
