
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-30T23:23:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f0fe54f73c4e397d1a75b7797d1222a76d6cd2b",
 "version": "1.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
