
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0d1f5bb3bce4f87c1e5818ce630c14c8c6311c45",
 "version": "v0.1.1-alpha.post.dev106"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
