
# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_short__',
    '__version_long__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_status__'
]

__version__ = '1.4.1a'
__version_short__ = '1.4.1a'
__version_long__ = '1.4.1a-0-gb72d2c58'
__version_post__ = '0'
__version_commit__ = 'b72d2c58'
__version_date__ = '2018-01-22 17:35:29 -0500'
__version_dirty__ = False
__build_date__ = '2018-07-30'
__build_time__ = '17:11:39.662037'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
