
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-28T16:17:58+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "2517c8d7d0ce08307f6d44c81e5eb88843262829",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
