
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-07T19:00:18-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d8aa0bf3f30612f85845bf50f13272adb8f0a91",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
