
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c98e315e5d126dae765552d4557f96a181253f7f",
 "version": "v0.1.1-alpha.post.dev109"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
