
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-09T11:35:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b8e16a4aebac96724b38f33ca130b8e42593caf",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
