# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20180404_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='geocode',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Geocode'),
        ),
        migrations.AddField(
            model_name='citytranslation',
            name='geocode',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Geocode'),
        ),
        migrations.AddField(
            model_name='country',
            name='geocode',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Geocode'),
        ),
        migrations.AddField(
            model_name='countrytranslations',
            name='geocode',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Geocode'),
        ),
        migrations.AddField(
            model_name='state',
            name='geocode',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Geocode'),
        ),
        migrations.AddField(
            model_name='statetranslation',
            name='geocode',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Geocode'),
        ),
    ]
