# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20180409_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='geocode',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Geocode'),
        ),
    ]
