- project:
    check:
      jobs:
        - senlin-dsvm-tempest-py27-api
        - senlin-dsvm-tempest-py35-api:
            voting: false
            branches: ^(?!stable/newton).*$
        - senlin-dsvm-tempest-py27-functional
        - senlin-dsvm-tempest-py35-functional:
            voting: false
            branches: ^(?!stable/newton).*$
        - senlin-dsvm-tempest-py27-integration:
            voting: false
        - senlin-dsvm-tempest-py35-integration:
            voting: false
            branches: ^(?!stable/newton).*$
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - senlin-dsvm-tempest-py27-api
        - senlin-dsvm-tempest-py27-functional
        - openstack-tox-lower-constraints
    experimental:
      jobs:
        - rally-dsvm-senlin-senlin:
            voting: false

- job:
    name: senlin-dsvm-tempest-py27-api
    parent: legacy-dsvm-base
    run: playbooks/legacy/senlin-dsvm-tempest-py27-api/run.yaml
    post-run: playbooks/legacy/senlin-dsvm-tempest-py27-api/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/senlin
      - openstack/senlin-tempest-plugin
      - openstack/tempest
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^senlin/tests/unit/.*$
      - ^releasenotes/.*$

- job:
    name: senlin-dsvm-tempest-py27-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/senlin-dsvm-tempest-py27-functional/run.yaml
    post-run: playbooks/legacy/senlin-dsvm-tempest-py27-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/heat
      - openstack/neutron-lbaas
      - openstack/python-zaqarclient
      - openstack/senlin
      - openstack/senlin-tempest-plugin
      - openstack/tempest
      - openstack/zaqar
      - openstack/zaqar-ui
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^senlin/tests/unit/.*$
      - ^releasenotes/.*$

- job:
    name: senlin-dsvm-tempest-py27-integration
    parent: legacy-dsvm-base
    run: playbooks/legacy/senlin-dsvm-tempest-py27-integration/run.yaml
    post-run: playbooks/legacy/senlin-dsvm-tempest-py27-integration/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/heat
      - openstack/neutron-lbaas
      - openstack/python-zaqarclient
      - openstack/senlin
      - openstack/senlin-tempest-plugin
      - openstack/tempest
      - openstack/zaqar
      - openstack/zaqar-ui
      - openstack/zaqar-tempest-plugin
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^senlin/tests/unit/.*$
      - ^releasenotes/.*$

- job:
    name: senlin-dsvm-tempest-py35-api
    parent: legacy-dsvm-base
    run: playbooks/legacy/senlin-dsvm-tempest-py35-api/run.yaml
    post-run: playbooks/legacy/senlin-dsvm-tempest-py35-api/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/senlin
      - openstack/senlin-tempest-plugin
      - openstack/tempest
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^senlin/tests/unit/.*$
      - ^releasenotes/.*$

- job:
    name: senlin-dsvm-tempest-py35-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/senlin-dsvm-tempest-py35-functional/run.yaml
    post-run: playbooks/legacy/senlin-dsvm-tempest-py35-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/heat
      - openstack/neutron-lbaas
      - openstack/python-zaqarclient
      - openstack/senlin
      - openstack/senlin-tempest-plugin
      - openstack/tempest
      - openstack/zaqar
      - openstack/zaqar-ui
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^senlin/tests/unit/.*$
      - ^releasenotes/.*$

- job:
    name: senlin-dsvm-tempest-py35-integration
    parent: legacy-dsvm-base
    run: playbooks/legacy/senlin-dsvm-tempest-py35-integration/run.yaml
    post-run: playbooks/legacy/senlin-dsvm-tempest-py35-integration/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/heat
      - openstack/neutron-lbaas
      - openstack/python-zaqarclient
      - openstack/senlin
      - openstack/senlin-tempest-plugin
      - openstack/tempest
      - openstack/zaqar
      - openstack/zaqar-ui
      - openstack/zaqar-tempest-plugin
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^senlin/tests/unit/.*$
      - ^releasenotes/.*$

- job:
    name: rally-dsvm-senlin-senlin
    parent: legacy-dsvm-base
    run: playbooks/legacy/rally-dsvm-senlin-senlin/run.yaml
    post-run: playbooks/legacy/rally-dsvm-senlin-senlin/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/diskimage-builder
      - openstack/ironic
      - openstack/magnum
      - openstack/networking-bgpvpn
      - openstack/neutron
      - openstack/neutron-fwaas
      - openstack/neutron-lbaas
      - openstack/neutron-vpnaas
      - openstack/octavia
      - openstack/panko
      - openstack/python-magnumclient
      - openstack/python-senlinclient
      - openstack/python-watcherclient
      - openstack/python-zaqarclient
      - openstack/rally
      - openstack/senlin
      - openstack/tripleo-image-elements
      - openstack/watcher
      - openstack/zaqar-ui
