- block:
  - name: Create python-tempestconf venv with latest pip, setuptools and pbr
    pip:
        virtualenv: "{{ virtualenvs.tempestconf }}"
        name: "{{ item }}"
        state: latest
    with_items:
        - pip
        - setuptools
        - pbr

  - name: Debug, list tempestconf dir
    shell: |
        set -ex
        ls -all .
        pwd
    args:
        chdir: "{{ tempestconf_src_relative_path }}"

  - name: Install python-tempestconf
    pip:
        name: "."
        virtualenv: "{{ virtualenvs.tempestconf }}"
        chdir: "{{ tempestconf_src_relative_path }}"

  - name: Generate tempest configuration file
    shell: |
        set -ex
        export PATH=$PATH:/usr/local/sbin:/usr/sbin
        source {{ virtualenvs.tempestconf }}/bin/activate
        printenv
        discover-tempest-config \
          --out etc/cloud_tempest.conf \
          --debug \
          -v \
          {% if cloud_user == "devstack-admin" %}
          --create \
          {% else %}
          --non-admin \
          {% endif %}
          --os-cloud {{ cloud_user }} \
          auth.tempest_roles Member
    args:
        chdir: "{{ tempestconf_src_relative_path }}"
        executable: /bin/bash

  - name: Print generated tempest.conf
    shell: |
        set -ex
        cat {{ tempestconf_src_relative_path }}/etc/cloud_tempest.conf

  vars:
    tempestconf_src_relative_path: "{{ zuul.projects['git.openstack.org/openstack/python-tempestconf'].src_dir }}"
