
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-15T16:56:12-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b11c07f425e916177c7080f0ba2e4b0530555a2",
 "version": "1.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
