
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c59028bf27d5ce187bc620b47a3f7778c5577323",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
