# Contains all of the processing parameters
# Note that this configuration file will be imported after the shared parameters config
# For more, see overwatch.base.config
#
# author: Raymond Ehlers <raymond.ehlers@cern.ch>, Yale University
# date: 16 July 2018

# Force each run to be reprinted and regenerate the pages.
forceReprocessing: false

# Select particular run numbers to be reprocessed
forceReprocessRuns: []

# Force the subsystem to be recreated during processing.
# This will allow the applied functions to be re-determined
forceRecreateSubsystem: false

# Force each run to be re-merged.
# Note that this can change the merging if new information has arrived since the last merge.
forceNewMerge: False

# Transfer data to the remote system.
sendData: False

# Set the type of merging based on the data we are receiving. If set to true, that means we are receiving
# cumulative files (i.e. the hists are not reset after they are sent by the HLT). In that case,
# to do a partial merge we take the last run file and subtract it from the first. 
cumulativeMode: True

# Specifies the prefix necessary to get to all of the folders.
# Don't include a trailing slash! (This may be mitigated by os.path calls, but not worth the
# risk in changing it).
dirPrefix: *dataFolder

# Username at remote system for sending data.
remoteUsername: ""

# Remote system hostnames.
# The number of entries in remoteSystems must match remoteFileLocations!
remoteSystems:
    - "aliceoverwatch.physics.yale.edu"

# Remote locations where to store the data files.
# The number of entries in each dict label must match remoteSystems!
remoteFileLocations:
    data:
        - "/opt/www/aliceoverwatch/data/"

