
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-31T17:50:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f3d44f45428c66bff5565ec815536428b3d6a8a9",
 "version": "1.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
