language: python
jobs:
  include:
    - stage:
      python: 3.6
      env: TOXENV=flake8
    - stage:
      python: 2.7
    - stage:
      python: 3.6
    - stage:
      python: pypy
    - stage:
      python: pypy3
    - stage: deploy
      python: 3.6
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: davehunt
        password:
          secure: "Y+EN7PN8BPGZD2+HUYSigYOlBd19/mpHcQ7kRJXL4MNh76nKAk6EFfPJ7afNvS1mgvnS8D+VKQDGWA/DxmxU2sHUzGVM5DPKfUeW+nKXQEBtNBVSUcP5gg7tXGwI6O0iTi2W8/tgK/DQNh91yS69h5l19F7Y20r10ckFa8fVAiRNE0bMVy+fkA9rNwZ/e/9Bv9cBBLxL0QzIrv2X0BUQ+GquzuZelm10we46bTWHPRbYMKJ6oj2hiDkxl4G0t+xNkvb6/QQnUCkm2YwL5+KgmRtEozNYbE5XIfqylR4ZRmdLzdFwpKl+6a0llCXjOq0abEFDZ7uf09ZMfoKuWj+EPFf2Pb2oQzAfsofqf+cLPj/+GNis4S6W5KsuyUFMaeEp5b3y0XhZlYi080WGVF5yhtAnQida3pAOGSsiFc22da4MqfQq1AHH3Ma8CdaHp47Yp0K/q1dOcgfixrsjzANeXh6dpz4/+ZcBxtdzoPkKBMp/vELTfGmpJ6d5AFlUdDepz2RFyHyvsjnwn2bqWK+rwjcsgXU/eIE1/Y55wPOR9/AACY+2mIdmk3yy55KfMXYbvSUK+yxjQxfh/tvp3XLRJ66JZn2viSsX5mB8mS75NIxBnpWxcwqzLkuyxB+q5YPWU4m9kPluPy066l9yUvLlWdo1qZDIL5h6bUw+zZcheAA="
        distributions: sdist bdist_wheel
        on:
          tags: true
          repo: mozilla/pytest-fxa
cache:
  pip: true
install: pip install tox-travis
script: tox
