
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-13T16:29:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "09a09d3c32f5ddaa2a596709a64720e1a770c8f5",
 "version": "0.17.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
