- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - lib-forward-testing
      - lib-forward-testing-python3
      - release-notes-jobs-python3
      - openstackclient-plugin-jobs
    check:
      jobs:
        - openstack-tox-lower-constraints
        - legacy-neutronclient-test-dsvm-functional:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^releasenotes/.*$
        - legacy-neutronclient-test-dsvm-functional-adv-svcs:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^releasenotes/.*$
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - legacy-neutronclient-test-dsvm-functional:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^releasenotes/.*$
        - legacy-neutronclient-test-dsvm-functional-adv-svcs:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^releasenotes/.*$
    post:
      jobs:
        - openstack-tox-cover
    experimental:
      jobs:
        - legacy-grenade-dsvm-neutron-libs:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$

