
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-23T11:30:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "afda79b2b5c7354b723f14a14329786e99306018",
 "version": "0.2.0.a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
