# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/intermake/intermake_qt/forms/designer/frm_maintenance_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(715, 469)
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PAGER_MAIN = QtWidgets.QStackedWidget(Dialog)
        self.PAGER_MAIN.setObjectName("PAGER_MAIN")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setStyleSheet("background: gray;\n"
"color: white;\n"
"font-size: 24px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.PAGER_MAIN.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.SPL_MAIN = QtWidgets.QSplitter(self.page)
        self.SPL_MAIN.setOrientation(QtCore.Qt.Vertical)
        self.SPL_MAIN.setHandleWidth(0)
        self.SPL_MAIN.setObjectName("SPL_MAIN")
        self.FRA_PROGRESS = QtWidgets.QFrame(self.SPL_MAIN)
        self.FRA_PROGRESS.setObjectName("FRA_PROGRESS")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.FRA_PROGRESS)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.TVW_LOG = QtWidgets.QTreeWidget(self.FRA_PROGRESS)
        self.TVW_LOG.setObjectName("TVW_LOG")
        self.TVW_LOG.headerItem().setText(0, "1")
        self.horizontalLayout_5.addWidget(self.TVW_LOG)
        self.frame = QtWidgets.QFrame(self.FRA_PROGRESS)
        self.frame.setProperty("style", "sidearea")
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.BTN_SHOW_PROGRESS = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_SHOW_PROGRESS.sizePolicy().hasHeightForWidth())
        self.BTN_SHOW_PROGRESS.setSizePolicy(sizePolicy)
        self.BTN_SHOW_PROGRESS.setMinimumSize(QtCore.QSize(24, 24))
        self.BTN_SHOW_PROGRESS.setMaximumSize(QtCore.QSize(24, 24))
        self.BTN_SHOW_PROGRESS.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/intermake/expanddown.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SHOW_PROGRESS.setIcon(icon)
        self.BTN_SHOW_PROGRESS.setCheckable(True)
        self.BTN_SHOW_PROGRESS.setAutoDefault(False)
        self.BTN_SHOW_PROGRESS.setFlat(True)
        self.BTN_SHOW_PROGRESS.setObjectName("BTN_SHOW_PROGRESS")
        self.verticalLayout_2.addWidget(self.BTN_SHOW_PROGRESS)
        self.BTN_ESTIMATE = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_ESTIMATE.sizePolicy().hasHeightForWidth())
        self.BTN_ESTIMATE.setSizePolicy(sizePolicy)
        self.BTN_ESTIMATE.setMinimumSize(QtCore.QSize(24, 24))
        self.BTN_ESTIMATE.setMaximumSize(QtCore.QSize(24, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/intermake/dropdown.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_ESTIMATE.setIcon(icon1)
        self.BTN_ESTIMATE.setAutoDefault(False)
        self.BTN_ESTIMATE.setFlat(True)
        self.BTN_ESTIMATE.setObjectName("BTN_ESTIMATE")
        self.verticalLayout_2.addWidget(self.BTN_ESTIMATE)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_5.addWidget(self.frame)
        self.FRA_MESSAGES = QtWidgets.QFrame(self.SPL_MAIN)
        self.FRA_MESSAGES.setObjectName("FRA_MESSAGES")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.FRA_MESSAGES)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.TXT_MESSAGES = QtWidgets.QTextEdit(self.FRA_MESSAGES)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.TXT_MESSAGES.setFont(font)
        self.TXT_MESSAGES.setStyleSheet("")
        self.TXT_MESSAGES.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.TXT_MESSAGES.setReadOnly(True)
        self.TXT_MESSAGES.setObjectName("TXT_MESSAGES")
        self.horizontalLayout_3.addWidget(self.TXT_MESSAGES)
        self.frame1 = QtWidgets.QFrame(self.FRA_MESSAGES)
        self.frame1.setProperty("style", "sidearea")
        self.frame1.setObjectName("frame1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.BTN_SHOW_OUTPUT = QtWidgets.QPushButton(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_SHOW_OUTPUT.sizePolicy().hasHeightForWidth())
        self.BTN_SHOW_OUTPUT.setSizePolicy(sizePolicy)
        self.BTN_SHOW_OUTPUT.setMinimumSize(QtCore.QSize(24, 24))
        self.BTN_SHOW_OUTPUT.setMaximumSize(QtCore.QSize(24, 24))
        self.BTN_SHOW_OUTPUT.setText("")
        self.BTN_SHOW_OUTPUT.setIcon(icon)
        self.BTN_SHOW_OUTPUT.setCheckable(True)
        self.BTN_SHOW_OUTPUT.setAutoDefault(False)
        self.BTN_SHOW_OUTPUT.setFlat(True)
        self.BTN_SHOW_OUTPUT.setObjectName("BTN_SHOW_OUTPUT")
        self.verticalLayout_3.addWidget(self.BTN_SHOW_OUTPUT)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.frame1)
        self.gridLayout.addWidget(self.SPL_MAIN, 0, 0, 1, 1)
        self.frame2 = QtWidgets.QFrame(self.page)
        self.frame2.setObjectName("frame2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BTN_CANCEL = QtWidgets.QPushButton(self.frame2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/resource_files/checkno.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CANCEL.setIcon(icon2)
        self.BTN_CANCEL.setAutoDefault(False)
        self.BTN_CANCEL.setObjectName("BTN_CANCEL")
        self.horizontalLayout_2.addWidget(self.BTN_CANCEL)
        spacerItem2 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.BTN_CLOSE = QtWidgets.QPushButton(self.frame2)
        self.BTN_CLOSE.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/resource_files/checkyes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CLOSE.setIcon(icon3)
        self.BTN_CLOSE.setAutoDefault(False)
        self.BTN_CLOSE.setDefault(True)
        self.BTN_CLOSE.setObjectName("BTN_CLOSE")
        self.horizontalLayout_2.addWidget(self.BTN_CLOSE)
        self.gridLayout.addWidget(self.frame2, 1, 0, 1, 1)
        self.PAGER_MAIN.addWidget(self.page)
        self.verticalLayout.addWidget(self.PAGER_MAIN)

        self.retranslateUi(Dialog)
        self.PAGER_MAIN.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Dialog", "<html>\n"
"<body>\n"
"\n"
"<img src=\":/intermake/wait.svg\" width=\"32\" height=\"32\" /><br/>\n"
"PLEASE WAIT\n"
"\n"
"</body>\n"
"</html>"))
        self.BTN_SHOW_PROGRESS.setToolTip(_translate("Dialog", "Expand view"))
        self.TXT_MESSAGES.setProperty("style", _translate("Dialog", "console"))
        self.BTN_SHOW_OUTPUT.setToolTip(_translate("Dialog", "Expand view"))
        self.BTN_CANCEL.setText(_translate("Dialog", "Cancel"))
        self.BTN_CLOSE.setText(_translate("Dialog", "Close"))


