- hosts: all
  name: gate-senlin-dsvm-tempest-py27-functional
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x

          export PYTHONUNBUFFERED=True
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_NOTESTS=1
          export DEVSTACK_GATE_EXERCISES=0
          export DEVSTACK_GATE_INSTALL_TESTONLY=1
          export KEEP_LOCALRC=1

          export DEVSTACK_GATE_USE_PYTHON3=False
          export SENLIN_TEST_TYPE="functional"
          export SENLIN_BACKEND="openstack_test"
          export DEVSTACK_GATE_TEMPEST_REGEX="senlin_tempest_plugin.tests.functional"

          services=rabbit,mysql,dstat,key,tempest
          services+=,g-api,g-reg
          services+=,n-api,n-cpu,n-cond,n-sch,n-crt
          if [[ "stable/newton" != $ZUUL_BRANCH ]]; then
            services+=,placement-api,placement-client
          fi
          services+=,q-svc,q-dhcp,q-meta,q-agt,q-l3

          export PROJECTS="openstack/senlin $PROJECTS"
          export DEVSTACK_LOCAL_CONFIG="enable_plugin senlin https://git.openstack.org/openstack/senlin"

          export PROJECTS="openstack/senlin-tempest-plugin $PROJECTS"
          export DEVSTACK_LOCAL_CONFIG+=$'\n'"TEMPEST_PLUGINS+=' /opt/stack/new/senlin-tempest-plugin'"

          export OVERRIDE_ENABLED_SERVICES=$services

          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          function pre_test_hook {
              cd /opt/stack/new/senlin/senlin/tests/tempest/
              source ./pre_test_hook.sh
          }
          export -f pre_test_hook

          function post_test_hook {
              cd /opt/stack/new/senlin/senlin/tests/tempest/
              source ./post_test_hook.sh
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
