- project:
    check:
      jobs:
        - karbor-dsvm-fullstack:
            voting: false

        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
- job:
    name: karbor-dsvm-fullstack
    parent: legacy-dsvm-base
    run: playbooks/legacy/karbor-dsvm-fullstack/run.yaml
    post-run: playbooks/legacy/karbor-dsvm-fullstack/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/karbor
      - openstack/python-karborclient
      - openstack/trove
      - openstack/trove-dashboard
      - openstack/manila-tempest-plugin
