# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-07 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('useragent', models.CharField(max_length=255, verbose_name='Useragent')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='IP Address')),
                ('get_data', models.TextField(verbose_name='GET Data')),
                ('post_data', models.TextField(verbose_name='POST Data')),
                ('http_accept', models.CharField(max_length=255, verbose_name='HTTP Accept')),
                ('path_info', models.CharField(max_length=255, verbose_name='Path')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Attempt created time')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
