
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "b2a73ba1d3b7a2e3fd3134ac611d098a74909070",
 "version": "v0.1.1-alpha.post.dev117"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
