__version__ = "2.0.7"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v2.0.7)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'c1bce3dff18c102ae33df1bb0a069ca3c26cd15f'
__git_head_subject__ = u'Finished Release v2.0.7'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2018-08-21 14:08:04'
