
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d92018a9262ac0639543633f432d3e59e950cd07",
 "version": "v0.1.1-alpha.post.dev108"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
