
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-20T00:16:32-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "858081a24dc1e123d7cb6ffa58a0495471a8b0bf",
 "version": "0.0.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
