
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-05T22:54:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d1f326f2c9d5b625f9d631fd7f5b7ef6ba988ee",
 "version": "1.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
