# Generated by Django 2.0.6 on 2018-06-26 18:11

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('fakenews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factcheck',
            name='tags',
        ),
        migrations.AddField(
            model_name='claim',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
