# Generated by Django 2.0.6 on 2018-06-26 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0003_auto_20180626_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
