# Generated by Django 2.0.6 on 2018-07-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0011_auto_20180709_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factcheck',
            name='headline',
            field=models.CharField(blank=True, help_text='A headline for the story (255 character limit)', max_length=255),
        ),
    ]
