# Generated by Django 2.0.6 on 2018-07-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0012_auto_20180709_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='slug',
        ),
    ]
