# Generated by Django 2.0.7 on 2018-08-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0016_auto_20180710_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
