# Generated by Django 2.0.7 on 2018-08-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0017_share_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='factcheck',
            name='rating',
        ),
        migrations.AddField(
            model_name='factcheck',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MediaType',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
