# Generated by Django 2.1 on 2018-08-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0018_auto_20180802_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='archive_url',
            field=models.URLField(blank=True, help_text='A permanent record of the claim being made'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='canoncial_url',
            field=models.URLField(blank=True, help_text='The original or most prominent spreading of the claim'),
        ),
    ]
