# Generated by Django 2.1 on 2018-08-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0020_auto_20180807_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
