# Generated by Django 2.1 on 2018-08-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0021_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='disinformationtype',
            name='color_light',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='disinformationtype',
            name='color_primary',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
