# Generated by Django 2.1 on 2018-08-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0023_auto_20180810_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factcheck',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
