# Generated by Django 2.1 on 2018-08-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0024_auto_20180810_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='text',
        ),
    ]
