- project:
    check:
      jobs:
        - barbican-simple-crypto-devstack-tempest
    gate:
      jobs:
        - barbican-simple-crypto-devstack-tempest
    experimental:
      jobs:
        - barbican-simple-crypto-devstack-tempest-py35
