# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallballapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='profile_type',
            field=models.CharField(choices=[(b'default', b'Default'), (b'gold', b'Gold')], default=b'default', max_length=12),
        ),
    ]
