# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fallballapp', '0003_clientuser_password_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='async',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='ready_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
