# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-02 06:13
from __future__ import unicode_literals

from django.db import migrations, models

from fallballapp.fixtures.load_data import load_data


class Migration(migrations.Migration):

    dependencies = [
        ('fallballapp', '0005_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='clientuser',
            unique_together=set([('client', 'user_id'), ('client', 'email')]),
        ),
        migrations.RunPython(load_data),
    ]
