# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-01 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallballapp', '0006_client_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
