# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 16:40
from __future__ import unicode_literals

from django.db import migrations, models


def rename(apps, schema_editor):
    ClientUser = apps.get_model('fallballapp', 'ClientUser')
    ClientUser.objects.filter(profile_type='default').update(profile_type='USERS')
    ClientUser.objects.filter(profile_type='gold').update(profile_type='GOLD_USERS')


class Migration(migrations.Migration):

    dependencies = [
        ('fallballapp', '0008_clientuser_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='profile_type',
            field=models.CharField(default=b'default', max_length=128),
        ),
        migrations.RunPython(rename),
    ]
