# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-16 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallballapp', '0009_custom_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='environment',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
