"""
Utils for cryptocurrencies addresses.
"""
BITCOIN_BECH32_PREFIX = 'bc1'
BITCOIN_P2PKH_PREFIX = '1'
BITCOIN_P2SH_PREFIX = '3'
MIN_BITCOIN_ADDRESS_LENGTH = 34
REQUIRED_BITCOIN_ADDRESS_LENGTH = 42

BITCOIN_CASH_NEW_PREFIXES = ('bitcoincash:p', 'bitcoincash:q')
BITCOIN_CASH_OLD_PREFIXES = ('1', '3')
REQUIRED_BITCOIN_CASH_NEW_ADDRESS_LENGTH = 54
REQUIRED_BITCOIN_CASH_OLD_ADDRESS_LENGTH = 34

HEX_PREFIX = '0x'
REQUIRED_ETHEREUM_ADDRESS_LENGTH = 42

LITECOIN_BECH32_PREFIX = 'ltc1'
LITECOIN_P2PKH_PREFIX = 'L'
LITECOIN_P2SH_PREFIX = 'M'
MIN_LITECOIN_ADDRESS_LENGTH = 34
REQUIRED_LITECOIN_ADDRESS_LENGTH = 42
