# Generated by Django 2.0.6 on 2018-06-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0002_auto_20180626_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='api_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
