# Generated by Django 2.0.6 on 2018-07-02 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0008_auto_20180702_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(help_text='A numerical value for the rating from 5 to 1', primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
