# Generated by Django 2.0.6 on 2018-07-02 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0009_auto_20180702_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='label',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(help_text='A numerical value for the rating from 1 to 5', primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
