# Generated by Django 2.0.6 on 2018-07-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0013_remove_source_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factcheck',
            name='publish_date',
            field=models.DateField(blank=True, help_text='The date this fact check was published.'),
        ),
        migrations.AlterField(
            model_name='share',
            name='publish_date',
            field=models.DateField(blank=True, help_text='The date this claim was spread by this source.'),
        ),
    ]
