# Generated by Django 2.0.6 on 2018-07-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0015_auto_20180710_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='factcheck',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='factcheck',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
