# Generated by Django 2.1 on 2018-08-07 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0019_auto_20180802_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factcheck',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
