# Generated by Django 2.1 on 2018-08-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0022_auto_20180808_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='factcheck',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
