# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GroupMeterGroupMemberChildDTO(Model):
    """GroupMeterGroupMemberChildDTO.

    :param meter_id: The meter identifier
    :type meter_id: int
    :param meter_code: The meter code
    :type meter_code: str
    :param meter_info: The meter info
    :type meter_info: str
    :param active: The flag determining whether the meter is active or not
    :type active: bool
    :param meter_type: The type of the meter
    :type meter_type: ~energycap.sdk.models.LogicalDeviceMeterTypeChildDTO
    :param commodity: The meter's commodity
    :type commodity: ~energycap.sdk.models.CommoditiesCommodityChildDTO
    :param place: The meter's parent place
    :type place: ~energycap.sdk.models.PlacePlaceChildDTO
    :param include_in_charts: The flag determining whether the meter is
     included in group charts
    :type include_in_charts: bool
    """

    _attribute_map = {
        'meter_id': {'key': 'meterId', 'type': 'int'},
        'meter_code': {'key': 'meterCode', 'type': 'str'},
        'meter_info': {'key': 'meterInfo', 'type': 'str'},
        'active': {'key': 'active', 'type': 'bool'},
        'meter_type': {'key': 'meterType', 'type': 'LogicalDeviceMeterTypeChildDTO'},
        'commodity': {'key': 'commodity', 'type': 'CommoditiesCommodityChildDTO'},
        'place': {'key': 'place', 'type': 'PlacePlaceChildDTO'},
        'include_in_charts': {'key': 'includeInCharts', 'type': 'bool'},
    }

    def __init__(self, meter_id=None, meter_code=None, meter_info=None, active=None, meter_type=None, commodity=None, place=None, include_in_charts=None):
        super(GroupMeterGroupMemberChildDTO, self).__init__()
        self.meter_id = meter_id
        self.meter_code = meter_code
        self.meter_info = meter_info
        self.active = active
        self.meter_type = meter_type
        self.commodity = commodity
        self.place = place
        self.include_in_charts = include_in_charts
