__title__ = 'openbanking'
__description__='Python 3 client SDK for UK Open Banking.'
__url__='https://getopenbanking.com/'
__version__='0.4.8'
__author__='Glyn Jackson'
__author_email__='me@glynjackson.org'
__license__='MIT'
__copyright__='Copyright 2018'