# Generated by Django 2.0.6 on 2018-06-23 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPageExtended',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]
