[tool.poetry]
name = "logconf"
version = "0.2.1"
description = "convenient python stdlib logging configuration"
authors = ["Andreas Lutro <anlutro@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
logging_tree = "*"
pycodestyle = "*"
pylint = "*"
pytest = "*"
pytest-pythonpath = "*"
