- project:
    check:
      jobs:
        - neutron-fwaas-networking-midonet-cross-py35:
            voting: false

        - openstack-tox-lower-constraints:
            required-projects:
              - openstack/neutron

        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/neutron
    gate:
      jobs:
        - openstack-tox-lower-constraints:
            required-projects:
              - openstack/neutron

        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/neutron
- job:
    name: neutron-fwaas-networking-midonet-cross-py35
    parent: openstack-tox-py35
    description: |
      Run Python 35 tests on networking-midonet repository.
    vars:
      zuul_work_dir: src/git.openstack.org/openstack/networking-midonet
    required-projects:
      - openstack/requirements
      - openstack/networking-midonet
      - openstack/neutron
      - openstack/neutron-vpnaas
      - openstack/neutron-lbaas
      - openstack/neutron-dynamic-routing
      - openstack/networking-l2gw
      - openstack/tap-as-a-service

- job:
    name: neutron-fwaas-fullstack
    parent: legacy-dsvm-base
    run: playbooks/neutron-fwaas-fullstack/run.yaml
    post-run: playbooks/neutron-fwaas-fullstack/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^releasenotes/.*$


- job:
    name: neutron-fwaas-fullstack-python35
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-fullstack-python35/run.yaml
    post-run: playbooks/legacy/neutron-fullstack-python35/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^releasenotes/.*$
    voting: false
