
# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_short__',
    '__version_long__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_status__'
]

__version__ = '1.3.5rc1'
__version_short__ = '1.3.5rc1'
__version_long__ = '1.3.5rc1-0-g2ed41bd2'
__version_post__ = '0'
__version_commit__ = '2ed41bd2'
__version_date__ = '2017-04-28 09:56:59 -0400'
__version_dirty__ = False
__build_date__ = '2018-07-30'
__build_time__ = '17:14:09.575049'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
