# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SearchSearchMeterChildDTOSearchMeterChild(Model):
    """SearchSearchMeterChildDTOSearchMeterChild.

    :param meter_id: The meter identifier
    :type meter_id: int
    :param meter_code: The meter code <span
     class='property-internal'>Required</span> <span
     class='property-internal'>Must be between 0 and 32 characters</span>
    :type meter_code: str
    :param meter_info: The meter info <span
     class='property-internal'>Required</span> <span
     class='property-internal'>Must be between 0 and 50 characters</span>
    :type meter_info: str
    :param accounts: The collection of accounts
    :type accounts:
     list[~energycap.sdk.models.LogicalDeviceMeterAccountChildDTO]
    :param commodity: The meter's commodity
    :type commodity: ~energycap.sdk.models.CommoditiesCommodityChildDTO
    :param meter_type: The type of the meter
    :type meter_type: ~energycap.sdk.models.LogicalDeviceMeterTypeChildDTO
    :param postal_code: The address postal code
    :type postal_code: str
    :param city: The address city
    :type city: str
    :param state: The address state
    :type state: str
    :param country: The address country
    :type country: str
    :param line1: The address first line
    :type line1: str
    :param line2: The address second line
    :type line2: str
    :param bill_entry_note: The bill entry note
    :type bill_entry_note: str
    :param include_in_energy_star: Indicates if the building is included in
     ENERGY STAR submissions
    :type include_in_energy_star: bool
    :param active: The flag determining whether the meter is active or not
    :type active: bool
    :param properties: An array of meter properties
    :type properties: dict[str, str]
    :param parent_path: The collection of places representing the path to its
     parent
    :type parent_path:
     list[~energycap.sdk.models.SearchSearchParentPlaceChildDTO]
    """

    _validation = {
        'meter_code': {'required': True, 'max_length': 32, 'min_length': 0},
        'meter_info': {'required': True, 'max_length': 50, 'min_length': 0},
    }

    _attribute_map = {
        'meter_id': {'key': 'meterId', 'type': 'int'},
        'meter_code': {'key': 'meterCode', 'type': 'str'},
        'meter_info': {'key': 'meterInfo', 'type': 'str'},
        'accounts': {'key': 'accounts', 'type': '[LogicalDeviceMeterAccountChildDTO]'},
        'commodity': {'key': 'commodity', 'type': 'CommoditiesCommodityChildDTO'},
        'meter_type': {'key': 'meterType', 'type': 'LogicalDeviceMeterTypeChildDTO'},
        'postal_code': {'key': 'postalCode', 'type': 'str'},
        'city': {'key': 'city', 'type': 'str'},
        'state': {'key': 'state', 'type': 'str'},
        'country': {'key': 'country', 'type': 'str'},
        'line1': {'key': 'line1', 'type': 'str'},
        'line2': {'key': 'line2', 'type': 'str'},
        'bill_entry_note': {'key': 'billEntryNote', 'type': 'str'},
        'include_in_energy_star': {'key': 'includeInEnergyStar', 'type': 'bool'},
        'active': {'key': 'active', 'type': 'bool'},
        'properties': {'key': 'properties', 'type': '{str}'},
        'parent_path': {'key': 'parentPath', 'type': '[SearchSearchParentPlaceChildDTO]'},
    }

    def __init__(self, meter_code, meter_info, meter_id=None, accounts=None, commodity=None, meter_type=None, postal_code=None, city=None, state=None, country=None, line1=None, line2=None, bill_entry_note=None, include_in_energy_star=None, active=None, properties=None, parent_path=None):
        super(SearchSearchMeterChildDTOSearchMeterChild, self).__init__()
        self.meter_id = meter_id
        self.meter_code = meter_code
        self.meter_info = meter_info
        self.accounts = accounts
        self.commodity = commodity
        self.meter_type = meter_type
        self.postal_code = postal_code
        self.city = city
        self.state = state
        self.country = country
        self.line1 = line1
        self.line2 = line2
        self.bill_entry_note = bill_entry_note
        self.include_in_energy_star = include_in_energy_star
        self.active = active
        self.properties = properties
        self.parent_path = parent_path
