language: python
sudo: false
dist: trusty
matrix:
 include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.5
    env: TOXENV=py35
#before_install:
  # Install tor and chutney if doing functional tests
  #- if [[ $TEST == 'functional' ]]; then ./test/scripts/install-tor.sh; fi
  #- if [[ $TEST == 'functional' ]]; then source test/scripts/install-chutney.sh; fi
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
