# coding: utf-8

"""
    FASva Data Management System API

    This is the API of the FASva management system.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint


import six


class Scene(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'idaggregation': 'int',
        'iddrive': 'int',
        'timestamp': 'datetime'
    }

    attribute_map = {
        'idaggregation': 'idaggregation',
        'iddrive': 'iddrive',
        'timestamp': 'timestamp'
    }

    def __init__(self, idaggregation=None, iddrive=None, timestamp=None):  # noqa: E501
        """Scene - a model defined in Swagger"""  # noqa: E501

        self._idaggregation = None
        self._iddrive = None
        self._timestamp = None
        self.discriminator = None

        if idaggregation is not None:
            self.idaggregation = idaggregation
        self.iddrive = iddrive
        self.timestamp = timestamp

    @property
    def idaggregation(self):
        """Gets the idaggregation of this Scene.  # noqa: E501


        :return: The idaggregation of this Scene.  # noqa: E501
        :rtype: int
        """
        return self._idaggregation

    @idaggregation.setter
    def idaggregation(self, idaggregation):
        """Sets the idaggregation of this Scene.


        :param idaggregation: The idaggregation of this Scene.  # noqa: E501
        :type: int
        """

        self._idaggregation = idaggregation

    @property
    def iddrive(self):
        """Gets the iddrive of this Scene.  # noqa: E501


        :return: The iddrive of this Scene.  # noqa: E501
        :rtype: int
        """
        return self._iddrive

    @iddrive.setter
    def iddrive(self, iddrive):
        """Sets the iddrive of this Scene.


        :param iddrive: The iddrive of this Scene.  # noqa: E501
        :type: int
        """
        if iddrive is None:
            raise ValueError("Invalid value for `iddrive`, must not be `None`")  # noqa: E501

        self._iddrive = iddrive

    @property
    def timestamp(self):
        """Gets the timestamp of this Scene.  # noqa: E501


        :return: The timestamp of this Scene.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this Scene.


        :param timestamp: The timestamp of this Scene.  # noqa: E501
        :type: datetime
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Scene):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
