# coding: utf-8

"""
    FASva Data Management System API

    This is the API of the FASva management system.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint


import six


class Sensor(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'additional_informations': 'object',
        'description': 'str',
        'idsensor': 'int',
        'parameter': 'str',
        'name': 'str'
    }

    attribute_map = {
        'additional_informations': 'additional_informations',
        'description': 'description',
        'idsensor': 'idsensor',
        'parameter': 'parameter',
        'name': 'name'
    }

    def __init__(self, additional_informations=None, description=None, idsensor=None, parameter=None, name=None):  # noqa: E501
        """Sensor - a model defined in Swagger"""  # noqa: E501

        self._additional_informations = None
        self._description = None
        self._idsensor = None
        self._parameter = None
        self._name = None
        self.discriminator = None

        if additional_informations is not None:
            self.additional_informations = additional_informations
        if description is not None:
            self.description = description
        if idsensor is not None:
            self.idsensor = idsensor
        if parameter is not None:
            self.parameter = parameter
        self.name = name

    @property
    def additional_informations(self):
        """Gets the additional_informations of this Sensor.  # noqa: E501


        :return: The additional_informations of this Sensor.  # noqa: E501
        :rtype: object
        """
        return self._additional_informations

    @additional_informations.setter
    def additional_informations(self, additional_informations):
        """Sets the additional_informations of this Sensor.


        :param additional_informations: The additional_informations of this Sensor.  # noqa: E501
        :type: object
        """

        self._additional_informations = additional_informations

    @property
    def description(self):
        """Gets the description of this Sensor.  # noqa: E501


        :return: The description of this Sensor.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Sensor.


        :param description: The description of this Sensor.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def idsensor(self):
        """Gets the idsensor of this Sensor.  # noqa: E501


        :return: The idsensor of this Sensor.  # noqa: E501
        :rtype: int
        """
        return self._idsensor

    @idsensor.setter
    def idsensor(self, idsensor):
        """Sets the idsensor of this Sensor.


        :param idsensor: The idsensor of this Sensor.  # noqa: E501
        :type: int
        """

        self._idsensor = idsensor

    @property
    def parameter(self):
        """Gets the parameter of this Sensor.  # noqa: E501


        :return: The parameter of this Sensor.  # noqa: E501
        :rtype: str
        """
        return self._parameter

    @parameter.setter
    def parameter(self, parameter):
        """Sets the parameter of this Sensor.


        :param parameter: The parameter of this Sensor.  # noqa: E501
        :type: str
        """

        self._parameter = parameter

    @property
    def name(self):
        """Gets the name of this Sensor.  # noqa: E501


        :return: The name of this Sensor.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Sensor.


        :param name: The name of this Sensor.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Sensor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
