
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-26T19:05:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "28df4c01f25ea01e06ffa298d9bee8bbdeb1ba8c",
 "version": "0.20.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
