
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-14T17:05:22-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fcb2a9e425f2bc873f3f32072b251de63a6e7edc",
 "version": "v0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
