
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-10T13:55:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "628b2a22a0ed02e23e4ec8018d0cd7bf190381ab",
 "version": "2018.09.10.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
