
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-17T14:54:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0f04e18c89821c2bfd1e1cd854b0c012b6579ad",
 "version": "0.0a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
