
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-04T16:13:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "938219b9d7bc88bbb6e2236b03563cf68856c9e1",
 "version": "v0.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
