[tool.poetry]
name = "red-connector-ssh"
version = "0.2"
authors = ["Christoph Jansen <Christoph.Jansen@htw-berlin.de>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/curious-containers/red-connector-ssh"
homepage = "https://curious-containers.github.io/"
description = "RED Connector SSH is part of the Curious Containers project."

[tool.poetry.dependencies]
python = "^3.4"
jsonschema = "^2.6"
paramiko = "^2.4"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
