
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-17T11:29:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d646ee9f8d704f33f6608761a42b5227754a515",
 "version": "0.2.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
