
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-22T17:24:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "44bf75cc51fe0c04deb67536497d887156ab11ca",
 "version": "1.8.2.post2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
