- project:
    check:
      jobs:
        - networking-midonet-tempest-aio-ml2:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^midonet/neutron/tests/unit/.*$
              - ^setup.cfg$
              - ^specs/.*$
        - networking-midonet-tempest-multinode-ml2:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^midonet/neutron/tests/unit/.*$
              - ^setup.cfg$
              - ^specs/.*$
        - networking-midonet-tempest-aio-ml2-full:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^midonet/neutron/tests/unit/.*$
              - ^setup.cfg$
              - ^specs/.*$
        - networking-midonet-tempest-aio-ml2-full-legacy:
            voting: false
            branches: ^(?!stable/(ocata|pike)).*$
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^midonet/neutron/tests/unit/.*$
              - ^setup.cfg$
              - ^specs/.*$
        - networking-midonet-tempest-aio-ml2-centos-7:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^midonet/neutron/tests/unit/.*$
              - ^setup.cfg$
              - ^specs/.*$
        - networking-midonet-tempest-aio-ml2-full-centos-7:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^midonet/neutron/tests/unit/.*$
              - ^setup.cfg$
              - ^specs/.*$
        - networking-midonet-grenade-ml2:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^midonet/neutron/tests/unit/.*$
              - ^setup.cfg$
              - ^specs/.*$
        - networking-midonet-rally-ml2:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^midonet/neutron/tests/unit/.*$
              - ^specs/.*$
    gate:
      jobs:
        - networking-midonet-tempest-aio-ml2:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^midonet/neutron/tests/unit/.*$
              - ^setup.cfg$
              - ^specs/.*$
        - networking-midonet-grenade-ml2:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^midonet/neutron/tests/unit/.*$
              - ^setup.cfg$
              - ^specs/.*$
        - networking-midonet-rally-ml2:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^midonet/neutron/tests/unit/.*$
              - ^specs/.*$

- job:
    name: networking-midonet-tempest-aio-ml2
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-l2gw
      - openstack/networking-midonet
      - openstack/neutron-dynamic-routing
      - openstack/neutron-tempest-plugin
      - openstack/tap-as-a-service
      - openstack/tempest

- job:
    name: networking-midonet-tempest-aio-ml2-centos-7
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2-centos-7/run.yaml
    post-run: playbooks/tempest-aio-ml2-centos-7/post.yaml
    timeout: 7800
    nodeset: legacy-centos-7
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-l2gw
      - openstack/networking-midonet
      - openstack/neutron-dynamic-routing
      - openstack/neutron-tempest-plugin
      - openstack/tap-as-a-service
      - openstack/tempest

- job:
    name: networking-midonet-tempest-aio-ml2-full
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2-full/run.yaml
    post-run: playbooks/tempest-aio-ml2-full/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-l2gw
      - openstack/networking-midonet
      - openstack/neutron-dynamic-routing
      - openstack/neutron-tempest-plugin
      - openstack/tap-as-a-service
      - openstack/tempest

- job:
    name: networking-midonet-tempest-aio-ml2-full-centos-7
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2-full-centos-7/run.yaml
    post-run: playbooks/tempest-aio-ml2-full-centos-7/post.yaml
    timeout: 7800
    nodeset: legacy-centos-7
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-l2gw
      - openstack/networking-midonet
      - openstack/neutron-dynamic-routing
      - openstack/neutron-tempest-plugin
      - openstack/tap-as-a-service
      - openstack/tempest

- job:
    name: networking-midonet-tempest-aio-ml2-full-legacy
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2-full-legacy/run.yaml
    post-run: playbooks/tempest-aio-ml2-full-legacy/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-l2gw
      - openstack/networking-midonet
      - openstack/neutron-dynamic-routing
      - openstack/neutron-tempest-plugin
      - openstack/tap-as-a-service
      - openstack/tempest

- job:
    name: networking-midonet-tempest-multinode-ml2
    parent: legacy-dsvm-base-multinode
    run: playbooks/tempest-multinode-ml2/run.yaml
    post-run: playbooks/tempest-multinode-ml2/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-l2gw
      - openstack/networking-midonet
      - openstack/neutron-dynamic-routing
      - openstack/neutron-tempest-plugin
      - openstack/tap-as-a-service
      - openstack/tempest
    nodeset: legacy-ubuntu-xenial-2-node

- job:
    name: networking-midonet-grenade-ml2
    parent: legacy-dsvm-base
    run: playbooks/grenade-ml2/run.yaml
    post-run: playbooks/grenade-ml2/post.yaml
    timeout: 9000
    required-projects:
      - openstack-dev/grenade
      - openstack-infra/devstack-gate
      - openstack/networking-midonet
      - openstack/neutron-tempest-plugin
    branches: ^(?!stable/ocata).*$

- job:
    name: networking-midonet-rally-ml2
    parent: legacy-dsvm-base
    run: playbooks/rally-ml2/run.yaml
    post-run: playbooks/rally-ml2/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-midonet
      - openstack/rally
