#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['scvelo',
 'scvelo.archive',
 'scvelo.plotting',
 'scvelo.preprocessing',
 'scvelo.tools']

package_data = \
{'': ['*']}

install_requires = \
['scanpy~=1.3.1', 'get_version', 'setuptools']

extras_require = \
{':extra == "doc"': ['docutils'], ':extra == "test"': ['pytest', 'loompy']}

setup(name='scvelo',
      version='0.1.4',
      description='scvelo - stochastic single cell RNA velocity',
      author='Volker Bergen',
      author_email='volker.bergen@helmholtz-muenchen.de',
      url='https://scvelo.readthedocs.io',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='~=3.6',
     )
