
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-21T01:52:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d5980ab8bb498ef47f01b9604b05b589736f3d7",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
