# coding: utf-8

"""
    FASva Data Management System API

    This is the API of the FASva management system.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fasvadms_client
from fasvadms_client.models.sensor import Sensor  # noqa: E501
from fasvadms_client.rest import ApiException


class TestSensor(unittest.TestCase):
    """Sensor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSensor(self):
        """Test Sensor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fasvadms_client.models.sensor.Sensor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
