# coding: utf-8

"""
    FASva Data Management System API

    This is the API of the FASva management system.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fasvadms_client
from fasvadms_client.api.vehicle_api import VehicleApi  # noqa: E501
from fasvadms_client.rest import ApiException


class TestVehicleApi(unittest.TestCase):
    """VehicleApi unit test stubs"""

    def setUp(self):
        self.api = fasvadms_client.api.vehicle_api.VehicleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_vehicle_by_name(self):
        """Test case for delete_vehicle_by_name

        Remove a vehicle by its name  # noqa: E501
        """
        pass

    def test_get_vehicle_by_id(self):
        """Test case for get_vehicle_by_id

        Get a vehicle by its id  # noqa: E501
        """
        pass

    def test_get_vehicle_by_name(self):
        """Test case for get_vehicle_by_name

        Get a vehicle by its name  # noqa: E501
        """
        pass

    def test_get_vehicle_list(self):
        """Test case for get_vehicle_list

        Get all vehicles  # noqa: E501
        """
        pass

    def test_post_vehicle_by_name(self):
        """Test case for post_vehicle_by_name

        Add a new vehicle with name `name`  # noqa: E501
        """
        pass

    def test_post_vehicle_list(self):
        """Test case for post_vehicle_list

        Add new vehicles  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
