sudo: true

language: python

python:
  - 3.5
  - 3.6
  - 3.4
  - 2.7

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - python -m pytest pycm/ --cov=pycm --cov-report=term
after_success:
  - codecov