
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-19T22:30:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "74921dd2b9f7f40ec9a5136cbb717a3580823a97",
 "version": "2.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
