
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-26T12:38:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6159b18cf9a19118d351dd37c8492abcb769ad90",
 "version": "v1.4.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
