
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d1b4e746ff3daba8d0e8d5163259462fc9298b9a",
 "version": "0.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
