
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-15T20:00:29-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d0ff804c2740c9467e9fb007fe56a92657c125b",
 "version": "v0.1.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
