
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-13T16:34:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f38dd348675aa52b3667570f482c72d5e60fd122",
 "version": "0.1.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
