#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='kieli',
      version='1.2.0',
      description='Minimalistic language server protocol client.',
      author='PurpleMyst',
      author_email='PurpleMyst@users.noreply.github.com',
      url='https://github.com/PurpleMyst/kieli',
      py_modules=['kieli'],
     )
