
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-03T08:52:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a6165678bd1dc74e48564a6a9687ab54c6952bd3",
 "version": "1.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
