
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-06T13:56:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd46b2d6e05753cdd30dc2c33ff312d4e7dd4b01",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
