
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "901ab061acadaf462abdd3928c3f6a2c4bdd48f1",
 "version": "1982"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
