
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-16T20:05:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6acdeebe902798723f1a6c8bd47fe196d4ead5c",
 "version": "0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
