# ============================================================================
# Config file for Quality Control
# ==========================================[ Sections for the users ]========
#
# One of input_directory, input_pattern and input_samples must be provided
# If input_directory provided, use it otherwise if input_pattern provided,
# use it, otherwise use input_samples.
# If input_extension provided, use it otherwise assume fastq.gz
# ============================================================================
input_directory: "%(input_directory)s"
input_readtag: "%(input_readtag)s"
input_extension: "%(input_extension)s"
input_pattern: "%(input_pattern)s"
input_samples: 
    file1: "%(file1)s"
    file2: "%(file2)s"


bam_to_fasta:
    thread: 6


######################################################
# Taxonomic analysis
#
# Provide as many databases as you want. They will be 
# used sequentially.
kraken:
    do: yes
    thread: 6
    db01_directory: toydb
    db02_directory: ''
    db03_directory: ''
    db04_directory: ''
    db05_directory: ''
    db06_directory: ''
    db07_directory: ''
    db08_directory: ''
    db09_directory: ''
    db10_directory: ''
