# Generated by Django 2.1 on 2018-08-25 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=128, unique=True, verbose_name='订单号')),
                ('goods', models.IntegerField(verbose_name='商品ID')),
                ('type', models.IntegerField(choices=[(1, '会员'), (2, '楼凤'), (3, '预定'), (4, '充值')], verbose_name='购买类别')),
                ('amount', models.FloatField(verbose_name='金额')),
                ('status', models.IntegerField(choices=[(1, '待付款'), (2, '已付款'), (3, '已作废')], verbose_name='状态')),
                ('pay_type', models.CharField(default='支付宝', max_length=32, verbose_name='支付方式')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单管理',
                'db_table': 'orders',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='viplogs',
            options={'ordering': ['-id'], 'verbose_name': 'VIP购买记录', 'verbose_name_plural': 'VIP购买记录管理'},
        ),
    ]
