# Generated by Django 2.1 on 2018-08-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('usercenter', '0002_auto_20180825_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sites.Site', verbose_name='所属站点'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, '待付款'), (2, '已付款'), (3, '已作废')], default=1, verbose_name='状态'),
        ),
    ]
