# Generated by Django 2.1 on 2018-08-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0003_auto_20180825_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='viplogs',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usercenter.Orders'),
        ),
    ]
