
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-06T07:28:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce32fa320dc6824b30b97b4ff8f76d4dae0dc9f7",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
