[tool.poetry]
name = "hugo"
version = "0.5.2"
description = "Discord bot library"
authors = ["Nariman Safiulin <woofilee@gmail.com>"]
license = "MIT"

readme = "README.md"
repository = "https://github.com/Roolat/hugo"

keywords = ["discord", "bot", "hugo"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Natural Language :: Russian",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.6"
"discord.py" = { git = "https://github.com/Rapptz/discord.py.git", branch = "rewrite" }

[tool.poetry.dev-dependencies]
black = "^18.3-alpha.0"
codecov = "^2.0"
coverage = "^4.5"
pre-commit = "^1.10"
pytest = "^3.7"
pytest-asyncio = "^0.9.0"
pytest-cov = "^2.5"
sphinx = "^1.7"
sphinx_rtd_theme = "^0.4.1"
sphinxcontrib-asyncio = "^0.2.0"
sphinxcontrib-napoleon = "^0.6.1"

[tool.black]
line-length = 80
py36 = true
