
# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_short__',
    '__version_long__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_status__'
]

__version__ = '1.3.1rc'
__version_short__ = '1.3.1rc'
__version_long__ = '1.3.1rc-0-g02e4c14b'
__version_post__ = '0'
__version_commit__ = '02e4c14b'
__version_date__ = '2017-02-04 13:46:42 -0500'
__version_dirty__ = False
__build_date__ = '2018-07-30'
__build_time__ = '17:11:31.502368'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
