# ============================================================================
# Config file for RNA-seq
#
# ==================[ Sections for the users ]================================
#
# One of input_directory, input_pattern and input_samples must be provided
# If input_directory provided, use it otherwise if input_pattern provided,
# use it, otherwise use input_samples.
# If input_extension provided, use it otherwise assume fastq.gz
# ============================================================================
input_directory: "%(input_directory)s"
input_readtag: "%(input_readtag)s"
input_pattern: "%(input_pattern)s"
input_extension: "%(input_extension)s"
# =========================================== Sections for the users

# list of your input file
input_samples:
    file1: "%(file1)s"
    file2: "%(file2)s"

# if files are required for a pipeline and are within sequana or should
# be downloaded before the pipeline provide them in this section
# Note that sequana and url fields are followed by itemised files or links
# using the front dashes
requirements:
    - Institut_Pasteur.png



#############################################################################
# Indexing section: if checked, all index for bowtie (1&2), star, etc... will be produced in dir
#
# :Parameters:
#
# - do: if unchecked, this rule is ignored
# - dir: directory where all indexed are written
# - name: name of prefix use in all mapping rules
# - fasta: path to Reference Genome in fasta format
#
genome:
  do: yes
  genome_directory: /path/to/your/directory
  name: "hg19" #path to index name
  fasta_file: /path/to/your/directory/Genomes/hg19/hg19.fa



#############################################################################
# star_mapping used to align reads against genome file
#
# :Parameters:
#
# - do: if unchecked, this rule is ignored
# - options: any options recognised by rna-star tool
# - threads: number of threads to be used
#
star_mapping:
    do: no
    options: "--outFilterMismatchNoverLmax 0.05 --outSAMunmapped Within "
    threads: 4
