# coding: utf-8
# Generated by setup.py for PyCBC on 2018-08-31 23:45:11 +0000.

version = '1.11.14'
date = '2018-08-31 22:42:46 +0000'
release = True
last_release = '1.11.14'

git_hash = 'b9c007220d4cd08698e05d8b812b9c800005736d'
git_branch = 'None'
git_tag = 'v1.11.14'
git_author = 'Josh Willis <josh-willis@users.noreply.github.com>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Travis CI User <travis@example.org>'
git_build_date = '2018-08-31 23:45:11 +0000'
git_verbose_msg = """Branch: None
Tag: v1.11.14
Id: b9c007220d4cd08698e05d8b812b9c800005736d
Builder: Travis CI User <travis@example.org>
Build date: 2018-08-31 23:45:11 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
