# Generated by Django 2.1 on 2018-09-07 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casl_django', '0002_auto_20180906_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caslpermission',
            name='action',
            field=models.TextField(help_text='Action', max_length=128),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='casl_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
