r"""
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmddhhhyyyyyyyyhhhddmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmdhyyyyyyyyyyyyyyyyyyyyyyyyyyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyydNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyydNMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyydNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyydNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMdyyyyyyyyyyyyyyyyyyyyyhdmmNNMMMMMMMMNNmmdhyyyyyyyyyyyyyyyyyyyyydMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNhyyyyyyyyyyyyyyyyyyhdNMMMMMMMMMMMMMMMMMMMMMMNdhyyyyyyyyyyyyyyyyyyhNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMmyyyyyyyyyyyyyyyyyhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhyyyyyyyyyyyyyyyyymMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMdyyyyyyyyyyyyyyyydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyyyyyyyyyyyyyyyydMMMMMMMMMMMMMM
MMMMMMMMMMMMMdyyyyyyyyyyyyyyyhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyyyyyyyyyyyyyyydMMMMMMMMMMMMM
MMMMMMMMMMMMdyyyyyyyyyyyyyyymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyyyyyyyyyyyyyyymMMMMMMMMMMMM
MMMMMMMMMMMNyyyyyyyyyyyyyyyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyyyyyyyyyyyyyyyNMMMMMMMMMMM
MMMMMMMMMMMhyyyyyyyyyyyyyyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyyyyyyyyyyyyyyhMMMMMMMMMMM
MMMMMMMMMMmyyyyyyyyyyyyyyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyyyyyyyyyyyyyymMMMMMMMMMM
mmmNNmNmmmmmmmmmmmmmmmmmmNNNmNNNmmNmNNmmmmmmmmmmNNNNNNNNNNmmmNNNmmmmNmmmmmmmmmmmmmmmmmmmmmNmmmNNNmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddmmmmmmmmmmmmddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmm`/mmms hs -hmm/.m/ --.-ym/ ---yy -:.+mh-.:/:-m/ :-.ymy-.:-./dm +mmmo dd `ymmo dd .--.+mmmmmmm
mmmmmmm`/mmms hs :`+m/.m/`mmmo h/`++ymy +s-.m`/mmyssm/`ys`oh +mmmd.-m +mmmo dd :`/do dd ommd./mmmmmm
mmmmmmm.:mmmo ds hh..-.m/`mmm+ d/`yyhmy +:`hm.:mmy: m/`o`-mh +mmmd.-m`/mmm+ md sd:`: dd ommd`/mmmmmm
mmmmmmmh--/:.sms hmmo .m/ --.:hm/ ---sy ymo`sd/.:/.-m/.md:.hy-.:-./dmy.-/:.smd smms` dd .--.+mmmmmmm
mmmmmmmmmdhdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddmmmmmmmmmmmmmddmmmmmmdhdmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmNNNNNNNNNm
MMMMMMMMMMmyyyyyyyyyyyyyyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyyyyyyyyyyyyyymMMMMMMMMMM
MMMMMMMMMMMhyyyyyyyyyyyyyyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyyyyyyyyyyyyyyhMMMMMMMMMMM
MMMMMMMMMMMNyyyyyyyyyyyyyyyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyyyyyyyyyyyyyyyNMMMMMMMMMMM
MMMMMMMMMMMMmyyyyyyyyyyyyyyymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyyyyyyyyyyyyyyymMMMMMMMMMMMM
MMMMMMMMMMMMMdyyyyyyyyyyyyyyyhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyyyyyyyyyyyyyyydMMMMMMMMMMMMM
MMMMMMMMMMMMMMdyyyyyyyyyyyyyyyyhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyyyyyyyyyyyyyyyydMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMmyyyyyyyyyyyyyyyyyhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhyyyyyyyyyyyyyyyyymMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNhyyyyyyyyyyyyyyyyyyhdNMMMMMMMMMMMMMMMMMMMMMMNdhyyyyyyyyyyyyyyyyyyhNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMdyyyyyyyyyyyyyyyyyyyyyhdmmNNMMMMMMMMNNmmdhyyyyyyyyyyyyyyyyyyyyydMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyydNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyydNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyydNMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyydNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmdhyyyyyyyyyyyyyyyyyyyyyyyyyyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmddhhhyyyyyyyyhhhddmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""

VERSION = (0, 1, 0, 'final', 0)

__title__ = 'django-allauth-underground'
__version_info__ = VERSION
__version__ = '.'.join(map(str, VERSION[:3])) + ('-{}{}'.format(
    VERSION[3], VERSION[4] or '') if VERSION[3] != 'final' else '')
__author__ = 'Biwin John'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Biwin John and original contributors'
