
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9aae976b9c4feb81eebf737b739b0490a34eec24",
 "version": "1990"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
