# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-29 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_db_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debuglog',
            options={'verbose_name': 'Error Log Entry', 'verbose_name_plural': 'Error Log Entries'},
        ),
        migrations.AlterModelOptions(
            name='errorlog',
            options={'verbose_name': 'Error Log Entry', 'verbose_name_plural': 'Error Log Entries'},
        ),
        migrations.AlterModelOptions(
            name='generallog',
            options={'verbose_name': 'Error Log Entry', 'verbose_name_plural': 'Error Log Entries'},
        ),
        migrations.AlterModelOptions(
            name='infolog',
            options={'verbose_name': 'Error Log Entry', 'verbose_name_plural': 'Error Log Entries'},
        ),
    ]
