
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "906195b921d445d29263b471423559f492bdb852",
 "version": "v0.1.1-alpha.post.dev125"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
