
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-31T15:05:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c351db0cad2501b1cee2d095b48dc93f8d27366",
 "version": "0.0a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
