
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-22T17:55:35+0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2886b03fe99dd132f17a7036bb4c4b7fff3507a5",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
