# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: container.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import variant_pb2
from . import database_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='container.proto',
  package='DBMessaging.Protobuf',
  serialized_pb=_b('\n\x0f\x63ontainer.proto\x12\x14\x44\x42Messaging.Protobuf\x1a\rvariant.proto\x1a\x0e\x64\x61tabase.proto\"\xb1\x08\n\tContainer\x12:\n\x0cmessage_type\x18\x01 \x01(\x0e\x32$.DBMessaging.Protobuf.Container.Type\x12\x44\n\x13signal_info_request\x18\x02 \x01(\x0b\x32\'.DBMessaging.Protobuf.SignalInfoRequest\x12\x46\n\x14signal_info_response\x18\x03 \x01(\x0b\x32(.DBMessaging.Protobuf.SignalInfoResponse\x12\x44\n\x13signal_data_request\x18\x04 \x01(\x0b\x32\'.DBMessaging.Protobuf.SignalDataRequest\x12\x46\n\x14signal_data_response\x18\x05 \x01(\x0b\x32(.DBMessaging.Protobuf.SignalDataResponse\x12N\n\x18\x63riterion_limits_request\x18\x06 \x01(\x0b\x32,.DBMessaging.Protobuf.CriterionLimitsRequest\x12P\n\x19\x63riterion_limits_response\x18\x07 \x01(\x0b\x32-.DBMessaging.Protobuf.CriterionLimitsResponse\x12=\n\x0fversion_request\x18\x08 \x01(\x0b\x32$.DBMessaging.Protobuf.VersionRequest\x12?\n\x10version_response\x18\t \x01(\x0b\x32%.DBMessaging.Protobuf.VersionResponse\x12*\n\x05\x65rror\x18\n \x01(\x0b\x32\x1b.DBMessaging.Protobuf.Error\x12\x37\n\x0ctime_request\x18\x0b \x01(\x0b\x32!.DBMessaging.Protobuf.TimeRequest\x12\x39\n\rtime_response\x18\x0c \x01(\x0b\x32\".DBMessaging.Protobuf.TimeResponse\"\xff\x01\n\x04Type\x12\x16\n\x12\x65SignalInfoRequest\x10\x01\x12\x17\n\x13\x65SignalInfoResponse\x10\x02\x12\x16\n\x12\x65SignalDataRequest\x10\x03\x12\x17\n\x13\x65SignalDataResponse\x10\x04\x12\x1b\n\x17\x65\x43riterionLimitsRequest\x10\x05\x12\x1c\n\x18\x65\x43riterionLimitsResponse\x10\x06\x12\x13\n\x0f\x65VersionRequest\x10\x07\x12\x14\n\x10\x65VersionResponse\x10\x08\x12\n\n\x06\x65\x45rror\x10\t\x12\x10\n\x0c\x65TimeRequest\x10\n\x12\x11\n\reTimeResponse\x10\x0b*\x08\x08\x64\x10\x80\x80\x80\x80\x02\x42\x1f\n\x1bno.icd.dbmessaging.protobufH\x03')
  ,
  dependencies=[variant_pb2.DESCRIPTOR,database_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CONTAINER_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='DBMessaging.Protobuf.Container.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='eSignalInfoRequest', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eSignalInfoResponse', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eSignalDataRequest', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eSignalDataResponse', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eCriterionLimitsRequest', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eCriterionLimitsResponse', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eVersionRequest', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eVersionResponse', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eError', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eTimeRequest', index=9, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eTimeResponse', index=10, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=881,
  serialized_end=1136,
)
_sym_db.RegisterEnumDescriptor(_CONTAINER_TYPE)


_CONTAINER = _descriptor.Descriptor(
  name='Container',
  full_name='DBMessaging.Protobuf.Container',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='DBMessaging.Protobuf.Container.message_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signal_info_request', full_name='DBMessaging.Protobuf.Container.signal_info_request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signal_info_response', full_name='DBMessaging.Protobuf.Container.signal_info_response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signal_data_request', full_name='DBMessaging.Protobuf.Container.signal_data_request', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signal_data_response', full_name='DBMessaging.Protobuf.Container.signal_data_response', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='criterion_limits_request', full_name='DBMessaging.Protobuf.Container.criterion_limits_request', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='criterion_limits_response', full_name='DBMessaging.Protobuf.Container.criterion_limits_response', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version_request', full_name='DBMessaging.Protobuf.Container.version_request', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version_response', full_name='DBMessaging.Protobuf.Container.version_response', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='DBMessaging.Protobuf.Container.error', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_request', full_name='DBMessaging.Protobuf.Container.time_request', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_response', full_name='DBMessaging.Protobuf.Container.time_response', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTAINER_TYPE,
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 536870912), ],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=1146,
)

_CONTAINER.fields_by_name['message_type'].enum_type = _CONTAINER_TYPE
_CONTAINER.fields_by_name['signal_info_request'].message_type = database_pb2._SIGNALINFOREQUEST
_CONTAINER.fields_by_name['signal_info_response'].message_type = database_pb2._SIGNALINFORESPONSE
_CONTAINER.fields_by_name['signal_data_request'].message_type = database_pb2._SIGNALDATAREQUEST
_CONTAINER.fields_by_name['signal_data_response'].message_type = database_pb2._SIGNALDATARESPONSE
_CONTAINER.fields_by_name['criterion_limits_request'].message_type = database_pb2._CRITERIONLIMITSREQUEST
_CONTAINER.fields_by_name['criterion_limits_response'].message_type = database_pb2._CRITERIONLIMITSRESPONSE
_CONTAINER.fields_by_name['version_request'].message_type = database_pb2._VERSIONREQUEST
_CONTAINER.fields_by_name['version_response'].message_type = database_pb2._VERSIONRESPONSE
_CONTAINER.fields_by_name['error'].message_type = database_pb2._ERROR
_CONTAINER.fields_by_name['time_request'].message_type = database_pb2._TIMEREQUEST
_CONTAINER.fields_by_name['time_response'].message_type = database_pb2._TIMERESPONSE
_CONTAINER_TYPE.containing_type = _CONTAINER
DESCRIPTOR.message_types_by_name['Container'] = _CONTAINER

Container = _reflection.GeneratedProtocolMessageType('Container', (_message.Message,), dict(
  DESCRIPTOR = _CONTAINER,
  __module__ = 'container_pb2'
  # @@protoc_insertion_point(class_scope:DBMessaging.Protobuf.Container)
  ))
_sym_db.RegisterMessage(Container)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033no.icd.dbmessaging.protobufH\003'))
# @@protoc_insertion_point(module_scope)
