apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: $app-$run
spec:
  replicas: 1
  template:
    metadata:
      labels:
        mlt-app-name: $app
    spec:
      containers:
        - image: $image
          name: tensorflow
          command : ["/bin/sh"]
          args : ["-c", "tensorboard --logdir $logdir"]

---
apiVersion: v1
kind: Service
metadata:
  name: $app-$run
spec:
  ports:
     -  port: 6006
        protocol: TCP
        targetPort: 6006
  selector:
    mlt-app-name: $app
  type: LoadBalancer
