
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "22e9bc92d803464ff6977e5b447d9c2f5baa7b75",
 "version": "2.0a6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
