
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-16T11:04:59-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac0236584abcbf20da31bd774dd40cf906f6f764",
 "version": "0.4.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
