
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7c04a201b440fc89836c478259f035ed0f870902",
 "version": "1988"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
