__version__ = "1.0.1"
__git_commiter_name__ = "Itai Shirav"
__git_commiter_email__ = "itais@infinidat.com"
__git_branch__ = u'(HEAD detached at v1.0.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '238fd11d6b04ad2c27f913b13ecfa790a727df7c'
__git_head_subject__ = u'Finished Release v1.0.1'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2018-08-13 08:46:10'
