version: 2
jobs:
    unit-test:
        docker:
            # Match target OS of TLJH
            - image: ubuntu:18.04

        steps:
            - checkout

            # Setup Python
            - run:
                name: install dependencies
                command: |
                    apt-get update --yes && apt-get install --yes python3 python3-venv git

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-py3.6-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}
                    - v1-dependencies-py3.6-

            - run:
                name: Setup venv
                command: |
                    python3 -m venv /srv/venv
                    echo 'export PATH=/srv/venv/bin:$PATH' >> $BASH_ENV

            - run:
                name: install dependencies
                command: |
                    pip install -r requirements.txt
                    pip install -r dev-requirements.txt
                    pip install -e .

            - save_cache:
                paths:
                    - /srv/venv/
                key: v1-dependencies-py3.6-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}

            - run:
                name: run unit tests
                command: |
                    py.test --cov=nbclean nbclean/tests/

            - run:
                name: upload code coverage stats
                command: |
                    codecov

workflows:
    version: 2
    all-tests:
        jobs:
            - unit-test
