
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-13T11:25:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d272bdca186499a62d09650058827355334cc93",
 "version": "v1.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
