schema = {
    "name": "kab",
    "type": "record",
    "fields": [
        {"start": 0,  "end": 2,  "type": "int", "name": "place_id"},
        {"start": 2,  "end": 4,  "type": "int", "name": "year"},
        {"start": 4,  "end": 5,  "type": "int", "name": "kai"},
        {"start": 5,  "end": 6,  "type": "string", "name": "nichi"},
        {"start": 6,  "end": 14, "type": "int", "name": "yyyymmdd"},
        {"start": 14, "end": 15, "type": "int", "name": "place_grouping_id"},
        {"start": 15, "end": 17, "type": "string", "name": "dow"},
        {"start": 17, "end": 21, "type": "string", "name": "place_name"},
        {"start": 21, "end": 22, "type": ["int", "null"], "name": "est_weather_id"},
        {"start": 22, "end": 23, "type": ["int", "null"], "name": "est_turf_track_cond_id"},
        {"start": 23, "end": 24, "type": ["int", "null"], "name": "est_turf_track_cond_speed_id"},
        {"start": 24, "end": 25, "type": ["int", "null"], "name": "est_turf_track_cond_id_1"},
        {"start": 25, "end": 26, "type": ["int", "null"], "name": "est_turf_track_cond_id_2"},
        {"start": 26, "end": 27, "type": ["int", "null"], "name": "est_turf_track_cond_id_3"},
        {"start": 27, "end": 30, "type": "int", "name": "est_turf_track_cond_speed_score"},
        {"start": 30, "end": 32, "type": "int", "name": "est_st_track_cond_spped_score_1"},
        {"start": 32, "end": 34, "type": "int", "name": "est_st_track_cond_spped_score_2"},
        {"start": 34, "end": 36, "type": "int", "name": "est_st_track_cond_spped_score_3"},
        {"start": 36, "end": 38, "type": "int", "name": "est_st_track_cond_spped_score_4"},
        {"start": 38, "end": 40, "type": "int", "name": "est_st_track_cond_spped_score_5"},
        {"start": 40, "end": 41, "type": ["int", "null"], "name": "est_dirt_track_cond_id"},
        {"start": 41, "end": 42, "type": ["int", "null"], "name": "est_dirt_track_cond_speed_id"},
        {"start": 42, "end": 43, "type": ["int", "null"], "name": "est_dirt_track_cond_id_1"},
        {"start": 43, "end": 44, "type": ["int", "null"], "name": "est_dirt_track_cond_id_2"},
        {"start": 44, "end": 45, "type": ["int", "null"], "name": "est_dirt_track_cond_id_3"},
        {"start": 45, "end": 48, "type": "int", "name": "est_dirt_track_cond_speed_score"},
        {"start": 48, "end": 49, "type": "int", "name": "kab_data_id"},
        {"start": 49, "end": 51, "type": "int", "name": "days"},
        {"start": 51, "end": 52, "type": ["int", "null"], "name": "turf_type_id"},
        {"start": 52, "end": 56, "type": "float", "name": "plant_height"},
        {"start": 56, "end": 57, "type": "int", "name": "compaction"},
        {"start": 57, "end": 58, "type": "int", "name": "anti_freezing"},
        {"start": 58, "end": 63, "type": "float", "name": "precipitation"}
    ]
}
