
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-06T11:37:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d48669dc912d39db5db2d2e72455352bb4ff3692",
 "version": "0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
