
"""
from nashit import data_fetchers
data_fetchers.nas_fetch_it("url","/path/to/save",".mp3")
"""
from time import sleep
sleep(0.02)
print("")
print("")
print("#################################")
sleep(0.02)
print("Donate at paypal.me/nashit93  ###")
sleep(0.02)
print("#################################")
print("                                    __,------._")
sleep(0.02)
print("                                .-'           ``-.")
sleep(0.02)
print("                            .' This guy has       `.")
sleep(0.02)
print("                            .' worked hard , would  :")
sleep(0.02)
print("                            ,'  u like to gift him  |")
sleep(0.02)
print("                        __,',-'`._  a coffee?     ,'")
sleep(0.02)
print("                        `--'      `-..______,--''")
sleep(0.02)
print("             )\       _  ")
sleep(0.02)
print("     .--._  ,' `\_.-~~/'        ")
sleep(0.02)
print("     `\    \'_    __ ( _ _ ")
sleep(0.02)
print("       `\   (_)  |__|/~ ~~=~\\")
sleep(0.02)
print("         )_____.---~~ \>\~-./'")
sleep(0.02)
print("        /'    //===  /==( ")
sleep(0.02)
print("       (     /' __\ ( __\) ")
sleep(0.02)
print("       ( /~\(   o   |_o_( ")
sleep(0.02)
print("       (( (         _____)")
sleep(0.02)
print("        \\_/     ,      )")
sleep(0.02)
print("         \ `\   ~-.._  /")
sleep(0.02)
print("        ._)/ \        /")
sleep(0.02)
print("         `/   \     ./")
sleep(0.02)
print("   NAS   /     `~/~' ")
sleep(0.02)
print("        /       /")
sleep(0.02)
print("       '~~-.__./                     ")

sleep(0.5)
print("")
sleep(0.02)
print("-------------------------------------")
sleep(0.02)
print("Basic Usage:                     ----")
sleep(0.02)
print("-------------------------------------")
print("")
print("")
sleep(0.02)
print("-------------------------------------")
sleep(0.02)
print("- Downloading Bulk Files From URL:---")
sleep(0.02)
print("-------------------------------------")
sleep(0.02)
print("    from nashit import data_fetchers")
sleep(0.02)
print("    data_fetchers.nas_fetch_it(\"url\",\"/path/to/save\",\".file_extension\")")
sleep(0.02)
print("")
#print("")
#print("")
sleep(0.02)