
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-29T16:00:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2dc4e2047ccc6a61609c2420e6154197537578f3",
 "version": "4.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
