# Generated by Django 2.0.6 on 2018-08-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('link', models.CharField(max_length=300, verbose_name='Link')),
                ('da', models.DateTimeField(auto_now_add=True, verbose_name='Date of create')),
                ('de', models.DateTimeField(auto_now=True, verbose_name='Date of last edit')),
            ],
            options={
                'verbose_name_plural': 'Social Networks',
                'ordering': ['-da'],
                'verbose_name': 'Social Network',
            },
        ),
    ]
