# Describes the format for available AIS drives services
browse_path:
  description: Listowanie zawartości (foldery i pliki) wskazanej ścieżki na dysku
  fields:
    path:
      description: Śeieżka
      example: '/sdcard/dom/Muzyka/Zalewski/Zelig'
