---
# KOPS ADDON
# WIKI: https://github.com/kubernetes/kops/tree/master/addons/route53-mapper
#
# This is a Kubernetes controller that polls services (in all namespaces) that are configured with the label dns=route53
# and adds the appropriate alias to the domain specified by the annotation domainName=sub.mydomain.io. Multiple domains
# and top level domains are also supported: domainName=.mydomain.io,sub1.mydomain.io,sub2.mydomain.io.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: route53-mapper
  namespace: kube-system
  labels:
    app: route53-mapper
    k8s-addon: route53-mapper.addons.k8s.io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: route53-mapper
  template:
    metadata:
      labels:
        app: route53-mapper
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicated", "value":"master"}]'
    spec:
      nodeSelector:
        kubernetes.io/role: master
      containers:
        - image: {{ component.image }}
          name: route53-mapper
