---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: kube-system
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: false
    ingress.kubernetes.io/app-root: /
spec:
  rules:
  - host: grafana.{{ settings.provision.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: monitoring-grafana
          servicePort: 80