kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: madcore-storage
  namespace: storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain

#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: madcore-storage
#  namespace: storage
#  annotations:
#    storageclass.kubernetes.io/is-default-class: "true"
#  labels:
#    addonmanager.kubernetes.io/mode: Reconcile
#provisioner: k8s.io/minikube-hostpath
#reclaimPolicy: Retain
