name: chemspipy
channels:
  - conda-forge
  - defaults
dependencies:
  - bumpversion=0.5.3
  - coverage=4.5.1
  - coveralls=1.3.0
  - m2r=0.2.0
  - requests=2.19.1
  - pytest=3.6.2
  - six=1.11.0
  - sphinx=1.7.5
  - sphinx_rtd_theme=0.4.1

