
# parent job is defined in openstack-manuals
- job:
    name: build-tox-manuals-buildpdf
    parent: build-tox-manuals
    vars:
      tox_envlist: buildpdf


- project:
    check:
      jobs:
        - build-tox-manuals-buildpdf
    gate:
      jobs:
        - build-tox-manuals-buildpdf
