
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-20T15:25:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fcbaa1ab6264e39a2aa0bee1984699cf69cee104",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
