# Generated by Django 2.0.7 on 2018-09-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casl_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caslpermission',
            name='action',
            field=models.TextField(help_text='Action', max_length=256),
        ),
    ]
