# Generated by Django 2.1 on 2018-08-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telethon_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
