# Generated by Django 2.1 on 2018-08-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telethon_django', '0002_auto_20180826_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='server_address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
