---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: scrapy-rc
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper.scrapy-rc:2181"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: scrapy-rc
  labels:
    app: kafka
spec:
  ports:
  - name: kafka
    port: 9092
  selector:
    app: kafka

