# Generated by Django 2.1 on 2018-08-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_reference', '0004_auto_20180116_1528'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reference',
            name='edc_referen_identif_351847_idx',
        ),
        migrations.RemoveIndex(
            model_name='reference',
            name='edc_referen_report__69deaa_idx',
        ),
        migrations.AlterIndexTogether(
            name='reference',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['identifier', 'timepoint', 'report_datetime', 'model', 'field_name'], name='edc_referen_identif_669fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['identifier', 'timepoint', 'report_datetime', 'model'], name='edc_referen_identif_311e28_idx'),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['timepoint', 'report_datetime'], name='edc_referen_timepoi_9bf87b_idx'),
        ),
    ]
