- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - monasca-tempest-python-influxdb
        - monasca-tempest-python-cassandra
        - monascalog-tempest
        - openstack-tox-docs:
            voting: false
    gate:
      queue: monasca
      jobs:
        - monasca-tempest-python-influxdb
        - monasca-tempest-python-cassandra
        - monascalog-tempest
