# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-13 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_staff', '0005_staffer_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffer',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
