---
- name: Create VM
  include_role:
    name: stackhpc.libvirt-vm
  vars:
    libvirt_vm_default_console_log_dir: "{{ log_directory }}"
    # Configure VM definitions for the Libvirt provider.
    libvirt_vms: >-
      {{ libvirt_nodes | map('set_libvirt_interfaces')
                       | map('set_libvirt_volume_pool')
                       | list }}
