
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "816c8b60580a9ccc6b3ce7652b09614e12514c7f",
 "version": "1984"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
