
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2018-08-28T19:41:01-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc53a296548489a755431ff30b559f98689114fb",
 "version": "1.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
