# coding: utf-8

"""
    Omnichannel API

    This is the beta version of Omnichannel API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: admin@messente.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import omnichannel_client
from omnichannel_client.models.sms import SMS  # noqa: E501
from omnichannel_client.rest import ApiException


class TestSMS(unittest.TestCase):
    """SMS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSMS(self):
        """Test SMS"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.sms.SMS()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
