# coding: utf-8

"""
    Omnichannel API

    This is the beta version of Omnichannel API  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: messente@messente.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import omnichannel
from omnichannel.models.error_item import ErrorItem  # noqa: E501
from omnichannel.rest import ApiException


class TestErrorItem(unittest.TestCase):
    """ErrorItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorItem(self):
        """Test ErrorItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = omnichannel.models.error_item.ErrorItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
