# coding: utf-8

"""
    Omnichannel API

    This is the beta version of Omnichannel API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: admin@messente.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import omnichannel_client
from omnichannel_client.models.omni_message_create_success_response import OmniMessageCreateSuccessResponse  # noqa: E501
from omnichannel_client.rest import ApiException


class TestOmniMessageCreateSuccessResponse(unittest.TestCase):
    """OmniMessageCreateSuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOmniMessageCreateSuccessResponse(self):
        """Test OmniMessageCreateSuccessResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.omni_message_create_success_response.OmniMessageCreateSuccessResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
