
# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_short__',
    '__version_long__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_status__'
]

__version__ = '1.7.4'
__version_short__ = '1.7.4'
__version_long__ = '1.7.4-0-g503b8e13'
__version_post__ = '0'
__version_commit__ = '503b8e13'
__version_date__ = '2017-01-19 10:09:41 -0500'
__version_dirty__ = False
__build_date__ = '2018-07-30'
__build_time__ = '16:41:24.371031'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
