
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "aa4b26747fb0e90d5d59e2a1f7eb731f448a9aae",
 "version": "v0.1.1-alpha.post.dev111"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
