
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-21T22:35:17-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7fb3ed9c89c570fe86cca24c72c40ec5bf25863",
 "version": "0.0.1.post.dev21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
