schema = {
    "name": "",
    "fields": [
        {"start": 0, "end": 2, "name": "place_id"},
        {"start": 2, "end": 4, "name": "year"},
        {"start": 4, "end": 5, "name": "kai"},
        {"start": 5, "end": 6, "name": "nichi"},
        {"start": 6, "end": 14, "name": "yyyymmdd"},
        {"start": 14, "end": 15, "name": "place_grouping_id"},
        {"start": 15, "end": 17, "name": "dow"},
        {"start": 17, "end": 21, "name": "place_name"},
        {"start": 21, "end": 22, "name": "est_weather_id"},
        {"start": 22, "end": 23, "name": "est_turf_track_cond_id"},
        {"start": 23, "end": 24, "name": "est_turf_track_cond_speed_id"},
        {"start": 24, "end": 25, "name": "est_turf_track_cond_id_1"},
        {"start": 25, "end": 26, "name": "est_turf_track_cond_id_2"},
        {"start": 26, "end": 27, "name": "est_turf_track_cond_id_3"},
        {"start": 27, "end": 30, "name": "est_turf_track_cond_speed_score"},
        {"start": 30, "end": 32, "name": "est_st_track_cond_spped_score_1"},
        {"start": 32, "end": 34, "name": "est_st_track_cond_spped_score_2"},
        {"start": 34, "end": 36, "name": "est_st_track_cond_spped_score_3"},
        {"start": 36, "end": 38, "name": "est_st_track_cond_spped_score_4"},
        {"start": 38, "end": 40, "name": "est_st_track_cond_spped_score_5"},
        {"start": 40, "end": 41, "name": "est_dirt_track_cond_id"},
        {"start": 41, "end": 42, "name": "est_dirt_track_cond_speed_id"},
        {"start": 42, "end": 43, "name": "est_dirt_track_cond_id_1"},
        {"start": 43, "end": 44, "name": "est_dirt_track_cond_id_2"},
        {"start": 44, "end": 45, "name": "est_dirt_track_cond_id_3"},
        {"start": 45, "end": 48, "name": "est_dirt_track_cond_speed_score"},
        {"start": 48, "end": 49, "name": "kab_data_id"},
        {"start": 49, "end": 51, "name": "days"},
        {"start": 51, "end": 52, "name": "turf_type_id"},
        {"start": 52, "end": 56, "name": "plant_height"},
        {"start": 56, "end": 57, "name": "compaction"},
        {"start": 57, "end": 58, "name": "anti_freezing"},
        {"start": 58, "end": 63, "name": "precipitation"}
    ]
}
