
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-30T13:34:01-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6116452b1353964d8581b222a3fc6a87c5e77b6a",
 "version": "1.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
