
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-15T14:57:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0dd4d7c5ee95a76230cac734ec630fcfb702538d",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
