
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-02T16:44:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b1bbf22a1bd07d1861fc83b64e1e5ea948dfeb93",
 "version": "0.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
