# -*- coding: UTF-8 -*-

# selenium
PARSE_SEARCH_WITH_DRIVER = False
BROWSER_WINDOW_SIZE = (1024, 768)
MAX_ATTEMPTS_TO_GET_PAGE = 10
WAIT_FOR_QUITING_DRIVER_TIME = 5
MAX_ATTEMPTS_TO_GET_COOKIES = 7
WAIT_PAGE_LOADING_TIME = 2.334
SOCKET_TIMEOUT = RESPONSE_TIMEOUT = PAGE_LOAD_TIMEOUT = 60.0
TIME_TO_LOAD_PHONE_WINDOW = 2
MAX_ATTEMPTS_TO_GET_COOKIES_AFTER_PARSING = 3

# processes and threads
TIME_TO_SLEEP_AFTER_PARSING = 15
DEFAULT_PROCESSES_KILL_TIMEOUT = 20
MAX_ATTEMPTS_TO_CATCH_EXECUTED_PROCESS = 3
TIME_TO_WAIT_PROCESS_EXECUTION = 3
