#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['geojson2fromto', 'geojson2fromto.library']

package_data = \
{'': ['*']}

entry_points = \
{'console_scripts': ['geojson2fromto = geojson2fromto:main']}

setup(name='geojson2fromto',
      version='0.2.1',
      description="Python module to convert GeoJSON to the 'from-to' format used by deck.gl's LineLayer",
      author='Weasel & Fox',
      author_email='hello@weaselandfox.com',
      url='https://github.com/weaselandfox/geojson2fromto',
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
     )
