[tool.poetry]
name = "tdsc"
version = "0.1.1"
description = ""
readme = "README.rst"
license = "MIT"
authors = ["Liam Dawson <liam@ldaws.com>"]
repository = "https://github.com/liamdawson/tdsc"
homepage = "https://github.com/liamdawson/tdsc"


[tool.poetry.dependencies]
python = ">=2.7,!=3.0,!=3.1,!=3.2,!=3.3,<4"
toml = "~0.9"
six = "~1.11"
distro = "^1.3"
appdirs = "^1.4"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
sphinx = "^1.7"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
