
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-08T21:15:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "56eddfc41f04295e61ebdb48ea2de642e1d80193",
 "version": "2018.3.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
