
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-13T16:13:10-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "04aee526a00d05d97c279aa9df490f6519f7d5cc",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
