[package]
name = "crfsuite-cabi"
version = "0.2.7"
authors = ["Messense Lv <messense@icloud.com>"]
publish = false

[dependencies]
backtrace = "0.3.5"
crfsuite = { path = "..", version = "0.2" }

[lib]
name = "pycrfsuite"
crate-type = ["cdylib"]

[profile.release]
debug = true
lto = true
